### PR TITLE
Server endpoint tests

### PR DESCRIPTION
**Pull request by chasestarr**
Add server endpoint tests
Add podcast lookup helper functions at /server/requestPodcastData.js
Add node-podcast-parser to package.json

Tests expect the parameters below

| Method | Endpoint | Expected response |
| --- | --- | --- |
| GET | /user/:username/subscriptions | Returns `object` with _subscriptions_ parameter containing list of channel ids |
| POST | /user/:username/subscriptions | Expects `integer` _channelId_. Returns `object` with _subscriptions_ parameter containing updated list of channel ids |
| GET | /user/:username | `object` user's public information. Currently checking for _username_ and _subscriptions_ fields |
| POST | /user | Expects `object` with _username_ and _subscriptions_ fields |
| GET | /channel/:channelId | Expects `integer` _channelId_. Returns parsed RSS feed with _title_, _description_, _image_, and _episodes_ |

### CODE REVIEW

**Comment by chasestarr** [comment]
Obviously the tests shouldn't pass for this PR

**Comment by willsimmons** [comment]
Should we save this one for later before merge? Now after looking at this code, I'm thinking we should pull out my simple one and throw it along with these, into a integration.js spec file, as the endpoint tests are a little more beyond that of a simple unit test. thoughts?

**Comment by chasestarr** [comment]
Huh, you're right that it's more of integration tests. I do think it's valuable to have these tests as a guide for developing the project. I can pull them out today into a separate integration.js

**Comment by chasestarr** [comment]
Moved route tests to integration.js
changed server.js name to dbSpec.js

**Review by willsimmons — APPROVED** [review]

**Pull request merged**
